import product1 from "../../public/product1.png";
import product4 from "../../public/advanced-ugv.webp";
import product2 from "../../public/vision-system.webp";
import product3 from "../../public/reach-v1.webp";


export const products = [
  {
    id: "1",
    title: "P3-R600-100",
    image: product1,
    Degrees_of_freedom: "6",
    Payload_kg: "3",
    Reach_mm: "540",
    Repeatability_mm: "A±0.03",
    Weight_kg: "13",
    IP_Classification: "IP54",
    Linear_Velocity_m_s: "1.5",
    Average_Power_W: "150",
    Peak_Power_W: "750",
    Ambient_Temperature: "0-60",
    Ambient_Humidity: "90% RH (non-condensing)",
    Installation_Orientation: "Any ceiling, floor, wall",
    Encoder_Resolution: "19Bit",
    Communication_Bus: "EtherCAT",
    Brake: "Friction Brake",
    Actuators: "J1, J2, J3",
    Max_Torque_Nm: "143NA-m",
    Rated_Torque_Nm: "31",
    Peak_Torque_Nm: "143",
    Motor_Power_W: "146",
    Max_Speed: "60RPM",
    Strain_Wave_Gear_Ratio: "14-100",
  },
  {
    id: "2",
    title: "P5-R900-120",
    image: product2,
    Degrees_of_freedom: "6",
    Payload_kg: "5",
    Reach_mm: "912",
    Repeatability_mm: "±0.03",
    Weight_kg: "23.5",
    IP_Classification: "IP54",
    Linear_Velocity_m_s: "3.0",
    Average_Power_W: "350",
    Peak_Power_W: "1500",
    "Ambient_Temperature_°C": "0-60",
    Ambient_Humidity: "90% RH (non-condensing)",
    Installation_Orientation: "Any ceiling, floor, wall",
    Encoder_Resolution: "19Bit",
    Communication_Bus: "EtherCAT",
    Brake: "Friction Brake",
    Actuators: "J1, J2, J3",
    Max_Torque_Nm: "107",
    Rated_Torque_Nm: "52",
    Peak_Torque_Nm: "191",
    Motor_Power_W: "300",
    Max_Speed_RPM: "60",
    Strain_Wave_Gear_Ratio: "20-100",
  },
  {
    id: "3",
    image: product3,
    title: "P5-R900-121",
    Degrees_of_freedom: "6",
    Payload_kg: "10",
    Reach_mm: "1300",
    Repeatability_mm: "±0.05",
    Weight_kg: "36.5",
    IP_Classification: "IP54",
    Linear_Velocity_m_s: "3.0",
    Average_Power_W: "500",
    Peak_Power_W: "2000",
    "Ambient_Temperature_°C": "0-60",
    Ambient_Humidity: "90% RH (non-condensing)",
    Installation_Orientation: "Any ceiling, floor, wall",
    Encoder_Resolution: "19Bit",
    Communication_Bus: "EtherCAT",
    Brake: "Friction Brake",
    Actuators: "J1, J2",
    Max_Torque_Nm: "143",
    Rated_Torque_Nm: "31",
    Peak_Torque_Nm: "143",
    Motor_Power_W: "146",
    Max_Speed_RPM: "60",
    Strain_Wave_Gear_Ratio: "14-100",
  },
  {
    id: "4",
    image: product4,
    title: "P5-R900-122",
    Degrees_of_freedom: "6",
    Payload_kg: "20",
    Reach_mm: "1650",
    Repeatability_mm: "±0.1",
    Weight_kg: "~58",
    IP_Classification: "IP54",
    Linear_Velocity_m_s: "~2.2",
    Average_Power_W: "1000",
    Peak_Power_W: "3000",
    "Ambient_Temperature_°C": "0-60",
    Ambient_Humidity: "90% RH (non-condensing)",
    Installation_Orientation: "Any ceiling, floor, wall",
    Encoder_Resolution: "19Bit",
    Communication_Bus: "EtherCAT",
    Brake: "Friction Brake",
    Actuators: "J1, J2",
    Max_Torque_Nm: "191",
    Rated_Torque_Nm: "52",
    Peak_Torque_Nm: "191",
    Motor_Power_W: "300",
    Max_Speed_RPM: "60",
    Strain_Wave_Gear_Ratio: "20-100",
  },
];
